version: "2.4"

services:
  nginx:
    image: nginx:1.21.6-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
  full_node:
    container_name: cere_full_node
    image: cerebellumnetwork/pos-node:v2.3.1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
    ports:
      - "9944:9944"
      - "9933:9933"
      - "30333:30333"
    volumes:
      - ./spec-data:/cereio/spec-data
      - ~/cere-data:/data
    command: bash -c "/usr/local/bin/cere -l${LOG_LEVEL} --name ${NODE_NAME} --chain /cereio/spec-data/${SPEC_PATH}/customSpecRaw.json --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' --bootnodes /ip4/${BOOT_NODE_IP_ADDRESS}/tcp/30333/p2p/${NETWORK_IDENTIFIER} /ip4/${BOOT_NODE_IP_ADDRESS_2}/tcp/30333/p2p/${NETWORK_IDENTIFIER_2} --ws-port 9944 --ws-external --rpc-methods=Auto --rpc-cors all --rpc-external"
  archive_node:
    container_name: cere_archive_node
    image: cerebellumnetwork/pos-node:v2.3.1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
    ports: 
      - "9944:9944"
      - "9933:9933"
      - "30333:30333"
    volumes:
      - ./spec-data:/cereio/spec-data
      - ~/cere-data:/data
    command: bash -c "/usr/local/bin/cere -l${LOG_LEVEL} --name ${NODE_NAME} --chain /cereio/spec-data/${SPEC_PATH}/customSpecRaw.json --pruning archive --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' --bootnodes /ip4/${BOOT_NODE_IP_ADDRESS}/tcp/30333/p2p/${NETWORK_IDENTIFIER} /ip4/${BOOT_NODE_IP_ADDRESS_2}/tcp/30333/p2p/${NETWORK_IDENTIFIER_2} --ws-port 9944 --rpc-methods=Unsafe --ws-external  --unsafe-ws-external --rpc-cors all --rpc-external"
  validator_node:
    container_name: cere_validator_node
    image: cerebellumnetwork/pos-node:v2.3.1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
    ports:
      - "127.0.0.1:9944:9944"
      - "127.0.0.1:9933:9933"
      - "30333:30333"
    volumes:
      - ./spec-data:/cereio/spec-data
      - ~/cere-data:/data
    command: bash -c "/usr/local/bin/cere -l${LOG_LEVEL} --name ${NODE_NAME} --chain /cereio/spec-data/${SPEC_PATH}/customSpecRaw.json --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' --validator --bootnodes /ip4/${BOOT_NODE_IP_ADDRESS}/tcp/30333/p2p/${NETWORK_IDENTIFIER} /ip4/${BOOT_NODE_IP_ADDRESS_2}/tcp/30333/p2p/${NETWORK_IDENTIFIER_2} --ws-port 9944 --rpc-methods=Unsafe --ws-external  --unsafe-ws-external --rpc-cors all --rpc-external"
