version: "2.4"

services:
  caddy:
    image: abiosoft/caddy:no-stats
    container_name: caddy
    restart: always
    environment:
      ACME_AGREE: "true"
    ports:
      - 9945:9945
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./caddy:/root/.caddy
  generate_sr_key:
    container_name: generate_sr_key
    build:
      context: ./
      dockerfile: Dockerfile.subkey
    command: bash -c "subkey generate --scheme sr25519"
  generate_ed_key:
    container_name: generate_ed_key
    build:
      context: ./
      dockerfile: Dockerfile.subkey
    command: bash -c "subkey inspect --scheme ed25519 ''"
  create_chain_spec:
    container_name: create_chain_spec
    image: cerebellumnetwork/pos-node:2.1.0-rc1
    volumes:
      - ./spec-data:/cereio/spec-data
    command: bash -c "mkdir -p ~/spec && /usr/local/bin/cere build-spec --disable-default-bootnode --chain local > /cereio/spec-data/customSpec.json"
  create_raw_chain_spec:
    container_name: create_raw_chain_spec
    image: cerebellumnetwork/pos-node:2.1.0-rc1
    volumes:
      - ./spec-data:/cereio/spec-data
    command: bash -c "/usr/local/bin/cere build-spec --chain=/cereio/spec-data/customSpec.json --raw --disable-default-bootnode > /cereio/spec-data/customSpecRaw.json"
  boot_node:
    container_name: boot_node
    image: cerebellumnetwork/pos-node:2.1.0-rc1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
    ports:
      - "9944:9944"
      - "9933:9933"
      - "30333:30333"
      - "9615:9615"
    volumes:
      - ./spec-data:/cereio/spec-data
      - ./chain-data:/data
    command: bash -c "/usr/local/bin/cere --prometheus-external --prometheus-port 9615 -l${LOG_LEVEL} --name ${NODE_NAME} --chain /cereio/spec-data/customSpecRaw.json --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' --validator --ws-port 9944 --rpc-methods=Unsafe --ws-external --unsafe-ws-external --rpc-cors all --rpc-external"
  add_validation_node_custom:
    container_name: add_validation_node_custom
    image: cerebellumnetwork/pos-node:2.1.0-rc1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
    ports:
      - "9944:9944"
      - "9933:9933"
      - "30333:30333"
      - "9615:9615"
    volumes:
      - ./spec-data:/cereio/spec-data
      - ./chain-data:/data
    command: bash -c "/usr/local/bin/cere --prometheus-external --prometheus-port 9615 -l${LOG_LEVEL} --name ${NODE_NAME} --chain /cereio/spec-data/customSpecRaw.json --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' --validator --bootnodes /ip4/${BOOT_NODE_IP_ADDRESS}/tcp/30333/p2p/${NETWORK_IDENTIFIER} --ws-port 9944 --rpc-methods=Unsafe --ws-external  --unsafe-ws-external --rpc-cors all --rpc-external"
  add_validator:
    container_name: add_validator
    image: add_validator_script
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
    build:
      context: ./
      dockerfile: Dockerfile.addValidator
    command: npm run add-validator
  generate_accounts:
    container_name: generate_accounts
    image: generate_accounts
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
    build:
      context: ./
      dockerfile: Dockerfile.generateAccounts
    volumes:
      - ./accounts:/app/accounts
      - ./scripts/keys:/keys
    command: npm run generate-accounts
  full_node:
    container_name: cere_full_node
    image: cerebellumnetwork/pos-node:2.1.0-rc1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
    ports:
      - "9944:9944"
      - "9933:9933"
      - "30333:30333"
      - "9615:9615"
    volumes:
      - ./spec-data:/cereio/spec-data
      - ./chain-data:/data
    command: bash -c "/usr/local/bin/cere --prometheus-external --prometheus-port 9615 -l${LOG_LEVEL} --name ${NODE_NAME} --chain /cereio/spec-data/customSpecRaw.json --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' --bootnodes /ip4/${BOOT_NODE_IP_ADDRESS}/tcp/30333/p2p/${NETWORK_IDENTIFIER} --ws-port 9944 --ws-external --rpc-methods=Auto --rpc-cors all --rpc-external"
  archive-node:
    container_name: cere_archive_node
    image: cerebellumnetwork/pos-node:2.1.0-rc1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
    ports: 
      - "9944:9944"
      - "9933:9933"
      - "30333:30333"
      - "9615:9615"
    volumes:
      - ./spec-data:/cereio/spec-data
      - ./chain-data:/data
    command: bash -c "/usr/local/bin/cere --prometheus-external --prometheus-port 9615 -l${LOG_LEVEL} --name ${NODE_NAME} --pruning archive --chain /cereio/spec-data/customSpecRaw.json --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' --bootnodes /ip4/${BOOT_NODE_IP_ADDRESS}/tcp/30333/p2p/${NETWORK_IDENTIFIER} --ws-port 9944 --ws-external --rpc-methods=Auto --rpc-cors all --rpc-external"
    
