#!/usr/bin/env bash

### validator

sed "s|PROVIDER=.*|PROVIDER=ws://add_validation_node_custom:9944|" .env
sed "s|STASH_ACCOUNT_MNEMONIC=.*|STASH_ACCOUNT_MNEMONIC=STASH_ACCOUNT_MNEMONIC|" .env
sed "s|CONTROLLER_ACCOUNT_MNEMONIC=.*|CONTROLLER_ACCOUNT_MNEMONIC=CONTROLLER_ACCOUNT_MNEMONIC|" .env